"""
Teacher governance utilities.

The teacher reviews plans generated by the agent, validates assignments,
and proposes remediation when the agent becomes stuck.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from igris.core import anti_loop, semantic_dedup


def build_teacher_payload(
    tasks: List[str],
    threshold: int = 3,
    last_test_result: Optional[Dict] = None,
    last_execution_report: Optional[Dict] = None,
    blocked_families: Optional[List[str]] = None,
    project_snapshot: Optional[Dict] = None,
) -> Dict[str, object]:
    """Assemble a rich payload summarising the state for the teacher."""
    recent_tasks = tasks[-20:]
    counts = anti_loop.compute_family_counts(tasks)
    saturated = anti_loop.saturated_families(counts, threshold=threshold)
    saturation_explanation = anti_loop.explain_saturation(tasks, threshold=threshold)

    current_family = None
    required_shift = None
    if tasks:
        current_family = anti_loop.classify_task_family(tasks[-1])
        required_shift = anti_loop.required_strategy_shift_family(
            current_family, tasks, threshold=threshold,
        )

    duplicate_info = None
    if tasks:
        is_dup, explanation = semantic_dedup.explain_duplicate(tasks[-1], tasks[:-1])
        duplicate_info = {"is_duplicate": is_dup, "explanation": explanation}

    return {
        "recent_tasks": recent_tasks,
        "family_counts": counts,
        "saturated_families": saturated,
        "blocked_families": blocked_families or [],
        "saturation_explanation": saturation_explanation,
        "current_family": current_family,
        "required_strategy_shift": required_shift,
        "duplicate": duplicate_info,
        "last_test_result": last_test_result,
        "last_execution_report": last_execution_report,
        "project_snapshot": project_snapshot,
        "policy": (
            "If a family is saturated and no concrete differentiator exists, "
            "the teacher MUST shift to a different family."
        ),
    }


def validate_teacher_assignment(assignment: Dict, history: List[str], threshold: int = 3) -> Dict:
    """Validate a teacher assignment against current constraints.

    Returns a dict with ``valid`` (bool) and ``reason`` (str).
    """
    family = assignment.get("selected_family", "other")
    differentiator = assignment.get("differentiator")
    success_criteria = assignment.get("success_criteria", [])

    counts = anti_loop.compute_family_counts(history)
    saturated = anti_loop.saturated_families(counts, threshold=threshold)

    if family in saturated and not differentiator:
        return {
            "valid": False,
            "reason": f"Family '{family}' is saturated and no differentiator provided",
        }

    if family in saturated and differentiator:
        # Check that differentiator is not just a restatement
        lowered = differentiator.lower().strip()
        if len(lowered) < 5:
            return {
                "valid": False,
                "reason": "Differentiator is too short to be meaningful",
            }

    # Observation loop detection
    if family == "other" and history:
        observation_count = sum(1 for t in history[-5:] if anti_loop.is_observation_like(t))
        task_desc = assignment.get("task_description", "")
        if anti_loop.is_observation_like(task_desc) and observation_count >= 3:
            return {
                "valid": False,
                "reason": "Observation loop detected — too many consecutive observation tasks",
            }

    if not success_criteria:
        return {"valid": False, "reason": "success_criteria are required"}

    return {"valid": True, "reason": "Assignment is valid"}


def propose_remediation_task(payload: Dict) -> Dict:
    """Propose a remediation task based on the teacher payload.

    When the current strategy is stuck, this function suggests shifting
    to a different family.
    """
    saturated = payload.get("saturated_families", [])
    current = payload.get("current_family")
    shift = payload.get("required_strategy_shift")
    last_test = payload.get("last_test_result")

    # If tests are failing, propose validation
    if last_test and not last_test.get("success", True):
        return {
            "task_title": "Remediation: fix failing tests",
            "task_description": "Tests are failing. Review test output and fix the issues.",
            "family": "testing",
            "reason": "Last test run failed",
            "differentiator": "Focus on failing test cases from last report",
            "success_criteria": ["All tests pass"],
            "safe_command_ids": ["run_tests"],
            "expected_next_state": "Tests green",
            "fallback_if_blocked": "Manual review of test output",
        }

    if shift:
        return {
            "task_title": f"Remediation: shift from '{current}' to '{shift}'",
            "task_description": (
                f"The current family '{current}' is saturated. "
                f"Switch strategy to the '{shift}' family."
            ),
            "family": shift,
            "reason": f"Family '{current}' is saturated",
            "differentiator": "Strategy shift due to saturation",
            "success_criteria": [f"Perform a task in the '{shift}' family"],
            "safe_command_ids": [],
            "expected_next_state": f"Active in '{shift}' family",
            "fallback_if_blocked": "Teacher manual review",
        }

    # If there are duplicate tasks, propose materialization
    dup_info = payload.get("duplicate")
    if dup_info and dup_info.get("is_duplicate"):
        return {
            "task_title": "Remediation: materialize unique task",
            "task_description": "Recent task appears to be a duplicate. Create a task with distinct goals.",
            "family": "other",
            "reason": "Duplicate task detected",
            "differentiator": "Must have concrete, unique success criteria",
            "success_criteria": ["Task has unique goals not covered by existing tasks"],
            "safe_command_ids": [],
            "expected_next_state": "New unique task created",
            "fallback_if_blocked": "Teacher assigns manually",
        }

    # Default: suggest a review
    return {
        "task_title": "Remediation: teacher review required",
        "task_description": "Unable to determine next step automatically. Teacher review needed.",
        "family": "other",
        "reason": "No specific issue detected",
        "differentiator": "Manual teacher intervention",
        "success_criteria": ["Teacher provides new direction"],
        "safe_command_ids": [],
        "expected_next_state": "Teacher provides guidance",
        "fallback_if_blocked": "Wait for teacher input",
    }
